### ISSUE TITLE
Investigate if tx fails to submit to Ethereum for WalletConnect users

### ISSUE THREAD

**Issue by amcassetti** [renproject/wbtc-cafe#6]
In response to two bug reports: 

**Bug Report 1** 
What product are you using?
WBTC Cafe (dApp)
What issue have you encountered?
swap operation is not completed.
What version of the SDK were you using?
N/A
What behaviour did you see?
Bitcoin transaction is completed. But swap does not happen.
What behaviour did you expect?
completion of the transaction :)
Please let us know the web browser version you are utilizing.
Chrome
Please let us know the Operating System (OS) version you are utilizing.
Macos
Can you please provide Etherscan and/or BlockCypher links to the transaction?
https://sochain.com/tx/BTC/400f0994172c7c283c1b92372421b3a09c400016e87a330b761cb1ce0ca66938
Please provide any relevant screenshots or file(s) that speak to the issue.
https://api.typeform.com/responses/files/7be7331c73f84645119a9416f9c1c4c4383fb9d776ffc8aa90c95cbb219ec561/wbtc.png

**Bug Report 2** 
What product are you using?
WBTC Cafe (dApp)
What issue have you encountered?
BTC -> WBTC stuck at Submitting to Ethereum (after successfully completed the BTC TX & having TX IDs)
What version of the SDK were you using?
N/A
What behaviour did you see?
As mentioned before
What behaviour did you expect?
Having a completed TX where I would receive WBTC in exchange of the BTC swapped
Please let us know the web browser version you are utilizing.
Chrome/Brave (tried both)
Please let us know the Operating System (OS) version you are utilizing.
Windows
Can you please provide Etherscan and/or BlockCypher links to the transaction?
https://sochain.com/tx/BTC/91cf4cc560758087f26f3d1908c42ce1044cd195a539cc9c718968e5f940984d (1st test TX 0.0005 BTC -> WBTC) and https://sochain.com/tx/BTC/4e3edd64dbcb6aedbdbe317ba41a1b8bcaea7205a915e2a7559246b9e5a1a4a5 (2nd test TX 0.004 BTC -> WBTC)
Please provide any relevant screenshots or file(s) that speak to the issue.
https://api.typeform.com/responses/files/ef1ab16259da986434e3f8246d5854ad3417e94aabb380d01594470df04ea0f4/IMG_20200712_125159_207.jpg

**Comment by TheAncientGoat** [comment]
Disabled WalletConnect for the time being in https://github.com/renproject/wbtc-cafe/pull/11 ; can be re-enabled with the `?walletConnectEnabled=true` query parameter, due to the reasoning below:

We need Ethereum wallets to work flawlessly to prevent issues with claiming mints, and as such they need to be tested extensively. All wallets could behave differently (the Trustwallet issue is related to needing to specify exact gas parameters), and not all of them supports testnets or custom networks making it slow & expensive to test thoroughly. WalletConnect enables a wide variety of wallets to connect that we cannot limit this to the wallets that we have tested, so we should hide it behind an advanced flag to discourage its use unless linked to via a supported wallet.
